http:
  port: "8081"
db:
  database: "mysql"
  user: "root"
  host: "localhost"
  password: "mysqlpw"
  port: '3306'
smtp:
  host: "smtp.gmail.com"
  port: "465"
  user: "noreply.coronais@gmail.com"
  password: "rvjaxdylbusbkmam"